Repository dawpitech/42sh, pull requests merged in 2024-05, with the labels that each got.

#24 [ADD] Parser lexer to main branch
  .gitignore
  Makefile
  bonus/alias.c
  bonus/alias.h
  bonus/display_parse.c
  include/builtins.h
  include/builtins_cmd.h
  include/lexer.h
  include/lexer_ast.h
  include/minishell.h
  include/parser.h
  include/path_explorer.h
  include/pipe_handler.h
  sources/IO/history.c
  sources/IO/path_explorer.c
  sources/IO/prompt.c
  sources/builtins/builtins_cmd.c
  sources/builtins/builtins_history.c
  sources/builtins/builtins_search_history.c
  sources/compute/compute_and.c
  sources/compute/compute_command.c
  sources/compute/compute_or.c
  sources/compute/compute_pipe.c
  sources/compute/compute_root.c
  sources/compute/compute_semicolon.c
  sources/minishell.c
  sources/parser/lexer.c
  sources/parser/my_parser.c
  sources/parser_ast/backtrack_lexer.c
  sources/parser_ast/lexer.c
  sources/parser_ast/lib_lexer/is_redirection.c
  sources/parser_ast/lib_lexer/my_is_operator.c
  sources/parser_ast/lib_lexer/my_isalpha_lexer.c
  sources/parser_ast/lib_lexer/my_isalphanum_lexer.c
  sources/parser_ast/lib_lexer/my_isand.c
  sources/parser_ast/lib_lexer/my_isparenthese.c
  sources/parser_ast/lib_lexer/my_ispipe.c
  sources/parser_ast/lib_lexer/my_issemicol.c
  sources/parser_ast/lib_lexer/my_isspace.c
  sources/parser_ast/lib_lexer/my_list_len.c
  sources/parser_ast/memory_management_parser/free_parser_lexer.c
  sources/parser_ast/memory_management_parser/init_parser_struct.c
  sources/parser_ast/parser.c
  sources/parser_ast/utils/and_utils.c
  sources/parser_ast/utils/handle_double_quote.c
  sources/parser_ast/utils/handle_operator.c
  sources/parser_ast/utils/handle_parenthese.c
  sources/parser_ast/utils/handle_single_quote.c
  sources/parser_ast/utils/or_utils.c
  sources/parser_ast/utils/pipe_utils.c
  sources/parser_ast/utils/redirect_utils.c
  sources/parser_ast/utils/root_utils.c
  sources/parser_ast/utils/semicol_utils.c
  sources/pipe_handler.c
  sources/runner/runner.c
Labels: enhancement

#33 Feature job controls
  Makefile
  include/builtins.h
  include/builtins_cmd.h
  include/minishell.h
  sources/IO/prompt.c
  sources/builtins/builtins_cmd.c
  sources/builtins/builtins_jobs_control.c
  sources/builtins/run_builtins.c
  sources/compute/compute_command.c
  sources/jobs_control/jobs_destroyer.c
  sources/jobs_control/jobs_manager.c
  sources/minishell.c
  sources/parser_ast/lexer.c
  sources/parser_ast/lib_lexer/my_isalphanum_lexer.c
  sources/parser_ast/memory_management_parser/free_parser_lexer.c
  sources/parser_ast/parser.c
  sources/parser_ast/utils/handle_parenthese.c
  sources/parser_ast/utils/pipe_utils.c
  sources/parser_ast/utils/root_utils.c
Labels: enhancement

#32 Add prompt navigation
  include/minishell.h
  sources/IO/prompt.c
Labels: enhancement

#38 Prompt navigation
  Makefile
  include/minishell.h
  sources/IO/prompt.c
  sources/IO/prompt_navigation.c
Labels: enhancement

#40 [UPDATE] Makefile and flake
  Makefile
  flake.lock
  flake.nix
Labels: enhancement

#45 [FIX] Input as not a tty
  Makefile
  include/minishell.h
  sources/IO/prompt.c
  sources/IO/prompt_navigation.c
  sources/IO/prompt_no_tty.c
Labels: bug

#46 [UPDATE] README.md
  README.md
  bonus/screenshot.png
Labels: documentation
